### ISSUE TITLE
可设置导入模板 输入行的 单元格格式。

### ISSUE THREAD

**Issue by rzlihaowei** [dotnetcore/Magicodes.IE#253] opened 2021-03-31 05:47 UTC
![image](https://user-images.githubusercontent.com/58129770/113096365-9a988a00-9227-11eb-9829-7d6d33b84570.png)

**Comment by hueifeng** [comment] 2021-04-12 16:45
#231 Duplicate of

**Comment by hueifeng** [comment] 2021-04-18 15:46
Now that this feature has been added, you can upgrade to the latest version.

```
dotnet add package Magicodes.IE.Excel --version 2.5.3.6
```
For example:
```
[ImporterHeader(Format ="@")]
```

**Closed by hueifeng** 2021-04-18 15:46 UTC
Labels: area-excel
